### ISSUE TITLE
Setters should return himself

### ISSUE THREAD

**Issue by HanXHX** [queue-interop/queue-interop#11]
Hello,

In [PsrMessage](https://github.com/queue-interop/queue-interop/blob/master/src/PsrMessage.php), setters should return "self".

Job is already done on PsrProducer.php

Cheers (and good work :+1:)

**Comment by makasim** [comment]
Could you please elaborate why?

**Comment by HanXHX** [comment]
Now you must:

```php
$message->setBody('body');
$message->setProperty('key', 'value');
$message->setHeader('h', 'v');
```
Expected (better readability):

```php
$message
    ->setBody($data)
    ->setProperty('key', 'value')
    ->setHeader('h', 'v');
```

**Comment by makasim** [comment]
I don't think worth it, good write up on the topic https://ocramius.github.io/blog/fluent-interfaces-are-evil/

**Comment by makasim** [comment]
The other point against the change it is a huge BC break as well as JMS does not do it either https://docs.oracle.com/javaee/7/api/javax/jms/Message.html#setBooleanProperty-java.lang.String-boolean-
