### ISSUE TITLE
Traits to implement Interfaces

### ISSUE THREAD

**Issue by sylfabre** [queue-interop/queue-interop#16]
Would you consider a PR with Trait to implement common methods defined by Interfaces?

I've in mind this [`Interop\Queue\Message`](https://github.com/queue-interop/queue-interop/blob/master/src/Message.php) interface.

Almost all implementations define the same method bodies which makes a lot of code duplicate that could be cleaned up.

**Comment by makasim** [comment]
Sure, it would be a good addition.
