### ISSUE TITLE
Interface names do not respect PSR

### ISSUE THREAD

**Issue by sylfabre** [queue-interop/queue-interop#18]
https://www.php-fig.org/bylaws/psr-naming-conventions/

They must be suffixed with Interface in a new 0.x version as it's not BC

**Comment by makasim** [comment]
There are little chances to get it to php-fig.

**Comment by sylfabre** [comment]
but would you consider a PR on this repo and another one on https://github.com/php-enqueue/enqueue-dev ?

**Comment by makasim** [comment]
I've just realised that master is 0.8 version. Your changes should be cherry picked to 0.7 branch (has current interfaces plus deprecated ones) BC is preserved. Could you do it? 

We could add `Interface` to be compatible with FIG (Though you know my opinion on it). B prepared fo huge amount of work as code base is relatively big.

**Comment by makasim** [comment]
@timrourke I tried to engage as many people as I could. I wrote about it on their mailing, tried to reach the FIG secretaries, tried to engage PHP frameworks. I've got nowhere. Here's the short list of my [proposals](https://github.com/queue-interop/queue-interop/issues/4).

I am open to it. If you want to step in you could surely rely on my support.

**Comment by kminek** [comment]
i'm huge fan of abstractions and this initiative is very cool. +1 for `Interface` suffix.
