### ISSUE TITLE
Message creation should not depend on context

### ISSUE THREAD

**Issue by gitomato** [queue-interop/queue-interop#7]
Hello,
Thanks for the initiative.

I have a suggestion. Object creations depend on `PsrContext `, which looks like a technical leak.
Also, it brings a strong dependency on the context.

This is the current interface:
```php
$context->createProducer()->send(
    $context->createQueue('aQueue'), 
    $context->createMessage('aBody')
);
```

With this interface, if I want to write a service pushing a message, it would either depend on:
- `PsrContext`, which is technical, and more than what I need (I don't want to consume the message there), 
- or `PsrProducer`, plus handwritten `QueueFactory` and `MessageFactory` to hide the context.

What about having `PsrMessage` and `PsrQueue` as plain PHP objects ?
```php
$context->createProducer()->send(
    new PsrQueue('aQueue'), 
    new PsrMessage('aBody')
);
```

Typically, I would let a dependency injection container manage `PsrProducer` instantiation.
Then, my business class would just depend on the producer to send messages. 

The producer being provided by the context has all necessary data to decorate the message and queue with technical information, without the end developer having to specify it.

This is in my opinion more DX.  It would also reduce the `PsrContext` interface responsibility to `PsrConsumer` and `PsrProducer` creation.

**Comment by makasim** [comment]
They should depend on context, cuz context is an implementation of an abstract fabric pattern. 
The queue, topic and message objects are not generic, each transport has its own set of them. 

https://github.com/php-enqueue/enqueue-dev/blob/master/pkg/redis/RedisProducer.php#L34-L35

> Typically, I would let a dependency injection container manage PsrProducer instantiation.
Then, my business class would just depend on the producer to send messages.

The other argument is `this is how it is implemented in Java JMS`.
