### ISSUE TITLE
Quick review of queue-interop with some comments

### ISSUE THREAD

**Issue by moufmouf** [queue-interop/queue-interop#9]
Hi @makasim 

I viewed queue-interop a few months ago but never had time to properly give some feedback when you started the project, sorry.

Having worked on PSR-11, I can give you a bit of advices if you ever want to push this on the PHP-FIG for a PSR. So here we go:

**PHP 5 vs PHP 7**:

I saw you discussed the issue here (#2). You decided to go for PHP 5 support a few month ago, but the tide has turned since then. Then newly passed PSR-15 is PHP 7+ only and upcoming PSR will be PHP 7+. So you should definitely target PHP 7 now.

**Naming**:

The interfaces are named `PsrXxx`. For instance `PsrMessage`. "Psr" does not add any value. On the other hand, you like the `Interface` suffix. I know many people feel it's wrong to have an `Interface` suffix (I'm part of those), but there has been a poll on the PHP-FIG mailing list 2 years ago and it was decided to go with the suffix.

So you should rename your interfaces this way:

- `PsrMessage` => `MessageInterface`

**Immutability**:

PSR-7 objects (RequestInterface and ResponseInterface) are immutable. This is a very nice property to have as it prevents a number of side-effect bugs. It could be useful to have that in Queue-interop also (so you could drop all the setters from Message and replace those with `withXxx` methods).

**Scope**:

This is a big one. I think your interfaces have way too many methods. You want to cover all the existing features of all queuing systems. Maybe you should rather target what all systems have in common (i.e. `send` and `consume`) rather than putting all possible features of all systems in your interface.

For instance:

`PsrProducer::setDeliveryDelay` seems highly suspicious to me. First of all, the "delivery delay" notion could belong to a message rather than to a producer. It can be nice for producers to have default values, but this is an implementation detail, it has nothing to do in an interface. Then, an interface with setters is usually a code smell (if you want to know why, see https://ocramius.github.io/extremely-defensive-php/)

I really don't have much time to look in depth at queue-interop, but if you can get some people interested on the PHP-FIG mailing list (I know, it's hard), I'm sure you could get a ton of feedback that would probably change quite radically the structure of your interfaces. I started this way with container-interop, and it's really a great learning opportunity when you have all those skilled people looking at your code. So give it another try and try to gather some more feeedback, it's worth it!

**Comment by makasim** [comment]
@moufmouf  Don't have time to answer though I surely do. 

Thanks for the feedback

**Comment by makasim** [comment]
* [x] PHP 5 vs PHP 7 - https://github.com/queue-interop/queue-interop/pull/13
* [ ] Naming - https://github.com/queue-interop/queue-interop/pull/14
* [ ] Immutability 
* [ ] Scope

**Comment by makasim** [comment]
> PsrProducer::setDeliveryDelay seems highly suspicious to me.

We followed [JMS specification here](https://docs.oracle.com/javaee/7/api/javax/jms/JMSProducer.html). It is a standard in Java world. 
It looked strange to me too, but having worked with that for some time I admit there is a logic behind that design.

**Comment by makasim** [comment]
> I really don't have much time to look in depth at queue-interop, but if you can get some people interested on the PHP-FIG mailing list (I know, it's hard)

Tried to mail on their mailing list, reach representatives and so on, without luck.

https://groups.google.com/forum/?fromgroups#!searchin/php-fig/queue%7Csort:date/php-fig/CcFN7zr90Wo/trM1Ii9KBAAJ
